FROM continuumio/miniconda3
LABEL maintainer="Cindy.vandeVriesSafaviNic@deltares.nl"
USER root

WORKDIR /root

# Do not bother with equestions
ENV DEBIAN_FRONTEND=noninteractive
# update system and install dependencies
RUN apt update \
    && apt install -y \
    davfs2  \
    vim \
    wget \
    curl \
    sudo \
    locales \
    fonts-liberation \
    ca-certificates \
    && apt-get clean && rm -rf /var/lib/apt/lists/*


# Update conda base environment
RUN conda update -n base -c defaults conda

# fix permission script
COPY scripts/fix-permissions /usr/local/bin/fix-permissions
RUN chmod a+rx /usr/local/bin/fix-permissions



# Define  users similar to  jupyter  notebook
ARG NB_USER="jovyan"
ARG NB_UID="1000"
ARG NB_GID="100"

RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
    locale-gen

# Configure environment
ENV CONDA_DIR=/opt/conda \
    SHELL=/bin/bash \
    NB_USER=$NB_USER \
    NB_UID=$NB_UID \
    NB_GID=$NB_GID \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8
ENV PATH=$CONDA_DIR/bin:$PATH \
    HOME=/home/$NB_USER

#  make place holder data directories
RUN mkdir -p /data/public && \
    mkdir -p /data/work && \
    mkdir -p /data/user


# TODO: add user with uid 1000 and gid 100
# Run the rest of this container as user 1000
RUN useradd -m -s /bin/bash -N -u $NB_UID $NB_USER &&  \
    mkdir -p $CONDA_DIR && \
    chown $NB_USER:$NB_GID $CONDA_DIR && \
    fix-permissions $HOME && \
    fix-permissions "$(dirname $CONDA_DIR)"


COPY scripts/startup.sh $HOME
# # The rest with pip
COPY . $HOME/app
# cleanup permissions because we copied as root
RUN fix-permissions $HOME


# Now we can
USER $NB_UID
WORKDIR $HOME


# Create a user environment

RUN conda create -n env python=3.7
RUN echo "source activate env" > ~/.bashrc
ENV PATH /opt/conda/envs/env/bin:$PATH
# Install packages with binary dependencies through conda
RUN conda config --add channels conda-forge && conda install -y matplotlib netCDF4 numpy pandas jupyter notebook pyproj




RUN pip install -r ./app/requirements.txt
RUN pip install -e ./app

# # # Expose port 5000

# # # Public datasets (~10GB)
VOLUME /data/public
# # # User dataset (? from nextcloud)
VOLUME /data/user
# # # Space to do some work (variable space  ~10GB)
VOLUME /data/work


EXPOSE 5000

HEALTHCHECK CMD curl --fail http://localhost:5000/health || exit 1
CMD ./startup.sh
