FROM continuumio/miniconda3
LABEL maintainer="Cindy.vandeVriesSafaviNic@deltares.nl"
USER root

WORKDIR /root

# Do not bother with equestions
ENV DEBIAN_FRONTEND=noninteractive
# update system and install dependencies
RUN apt update && \
    apt install -y davfs2  vim wget curl

# Install packages with binary dependencies through conda
RUN conda config --add channels conda-forge && conda install matplotlib netCDF4 numpy pandas jupyter notebook pyproj

COPY scripts/startup.sh .

# The rest with pip
COPY . ./app

RUN pip install -r ./app/requirements.txt
RUN pip install -e ./app

# Expose port 5000
EXPOSE 5000
CMD ./startup.sh
