#!/bin/sh
# print ENV variables
echo "URL is $WEBDAV_URL"

if [ -z "${WEBDAV_USERNAME}" ];
then
    echo "WEBDAV_USERNAME is unset or set to the empty string"
fi

if [ -z "${WEBDAV_PASSWORD}" ];
then
    echo "WEBDAV_PASSWORD is unset or set to the empty string"
fi


if [ ! -z "${WEBDAV_USERNAME}" -a ! -z "${WEBDAV_PASSWORD}" ];
then
    # Create entry in secrets file
    echo "$WEBDAV_URL $WEBDAV_USERNAME $WEBDAV_PASSWORD" >> /etc/davfs2/secrets

    # make dir for mount
    mkdir -p ~/work/b2drop

    # make sure /etc/mtab exists
    touch /etc/mtab

    # mount b2drop to dir
    mount -t davfs $WEBDAV_URL ~/work/b2drop
fi
